workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
    - when: never

stages:
  - build
  - release
  - tests

build-container:
  stage: build
  tags:
    - blockchain-docker
  script:
    - > 
      if [ $CI_COMMIT_BRANCH == "master" ] ; then
         make --directory=ci/ container  ;
      fi 

release-registry:
  stage: release
  tags:
    - blockchain-docker 
  before_script:
    - docker login -u $DOCKER_TESTER_LOGIN -p $DOCKER_TESTER_PASSWORD registry.i.sumus.work 
  script:
    - > 
      if [ $CI_COMMIT_BRANCH == "master" ] ; then
         make --directory=ci/ release ;
      fi  

deploy-tests:
  stage: tests
  variables:
    GIT_STRATEGY: none
    HOSTNAME: demo-testing.moutai.k8s.clive.tk
    RESULT_NAME: front_tests
  tags:
    - blockchain-docker
  script:
    - set -x
    - mkdir -p results
    - cd ci/
    - docker-compose up -d
    - sleep 40
  artifacts:
    paths:
      - $CI_PROJECT_DIR/results/$RESULT_NAME.xml
    expire_in: 30 minutes
    reports:
      junit: $CI_PROJECT_DIR/results/$RESULT_NAME.xml