workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
    - when: never

stages:
  - build
  - release
  - tests
  - clean

build-container:
  stage: build
  tags:
    - blockchain-docker
  script:
    - > 
      if [ $CI_COMMIT_BRANCH == "master" ] ; then
         make --directory=ci/ container  ;
      fi 

release-registry:
  stage: release
  tags:
    - blockchain-docker 
  before_script:
    - docker login -u $DOCKER_TESTER_LOGIN -p $DOCKER_TESTER_PASSWORD registry.i.sumus.work 
  script:
    - > 
      if [ $CI_COMMIT_BRANCH == "master" ] ; then
         make --directory=ci/ release ;
      fi  

run-tests:
  stage: tests
  variables:
    GIT_STRATEGY: none
    HOSTNAME: demo-testing.moutai.k8s.clive.tk
    RESULT_NAME: front_test
  tags:
    - blockchain-docker
  script:
    - set -x
    - test -d results/ || mkdir -p results
    - touch results/$RESULT_NAME.xml
    - cd ci/
    - docker-compose up -d
    - >
      while [ ! -s ../results/$RESULT_NAME.xml ] ; do
        echo "Tests not passed yet..."
        sleep 5 ;
      done 
    - ls -l ../results
  artifacts:
    paths:
      - $CI_PROJECT_DIR/results/$RESULT_NAME.xml
    expire_in: 30 minutes
    reports:
      junit: $CI_PROJECT_DIR/results/$RESULT_NAME.xml

clean:
  stage: clean
  tags:
    - blockchain-docker
  script:
    - test ! -d || rm -rf results/
    - docker stop selenium
  when: always