workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
    - when: never

stages:
  - build
  - release
  - tests

build-container:
  stage: build
  tags:
    - blockchain-docker
  script:
    - > 
      if [ $CI_COMMIT_BRANCH == "master" ] ; then
         make --directory=ci/ container  ;
      fi 

release-registry:
  stage: release
  tags:
    - blockchain-docker 
  before_script:
    - docker login -u $DOCKER_TESTER_LOGIN -p $DOCKER_TESTER_PASSWORD registry.i.sumus.work 
  script:
    - > 
      if [ $CI_COMMIT_BRANCH == "master" ] ; then
         make --directory=ci/ release ;
      fi  

deploy-tests:
  stage: tests
  variables:
    GIT_STRATEGY: none
  tags:
    - blockchain-docker
  script:
    - set +x
    - cd ci/
    - HOSTNAME=demo-testing.moutai.k8s.clive.tk
    - docker-compose up -d
    - sleep 60
  artifacts:
    paths:
      - "../results/front_test.xml"
    expire_in: 30 minutes
    reports:
      junit: ../results/front_test.xml