workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
    - when: never

stages:
  - build
  - release

build-container:
  stage: build
  tags:
    - blockchain-docker
  script:
    - > 
      if [ $CI_COMMIT_BRANCH == "master" ] ; then
         make --directory=ci/ container  ;
      fi 

release-registry:
  stage: release
  tags:
    - blockchain-docker 
  before_script:
    - docker login -u $DOCKER_TESTER_LOGIN -p $DOCKER_TESTER_PASSWORD registry.i.sumus.work 
  script:
    - > 
      if [ $CI_COMMIT_BRANCH == "master" ] ; then
         make --directory=ci/ release ;
      fi  